version: 0.2

phases:
  install:
    runtime-versions:
      java: openjdk8
  build:
    commands:
      - echo Build started on `date`
      - ./gradlew clean build install
artifacts:
  files:
    - target/*.jar