
description = 'paper-helper'

dependencies {
  implementation project(':bukkit-helper')
  implementation project(':dynmap-api')
  implementation project(path: ':DynmapCore', configuration: 'shadow')
  implementation group: 'com.destroystokyo.paper', name: 'paper-api', version:'1.12.2-R0.1-SNAPSHOT'
}
